name: Ubuntu

on:
  push:
    branches: [ main, self-hosted-runner ]
  pull_request:
    branches: [ main, self-hosted-runner ]
  workflow_dispatch:

env:
  build_dir: "build"
  artifact: "cuboolgraph-ubuntu-build.tar.xz"

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            gcc: 14

    env:
      config: "Release"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure CMake build
        run: |
          cmake -B ${{ env.build_dir }} -S .               \
                -DCMAKE_CXX_COMPILER=g++-${{ matrix.gcc }} \
                -DCMAKE_C_COMPILER=gcc-${{ matrix.gcc }}   \
                -DCMAKE_BUILD_TYPE=${{ env.config }}       \
                -DCUBOOL_BUILD_TESTS=ON                    \
                -DCUBOOL_WITH_CUDA=OFF                     \
                -DCUBOOL_WITH_SEQUENTIAL=ON                \
                -DCUBOOL_GRAPH_ENABLE_TESTING=ON

      - name: Build library sources
        run: |
          cmake --build ${{ env.build_dir }} \
                --verbose \
                -j10

      - name: Prepare upload binary
        run: |
          tar cfz ${{ env.artifact }} ${{ env.build_dir }}

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact }}
          path: ${{ env.artifact }}

  test:
    name: Test CPU ${{ matrix.cpu }}
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            cpu: AMD-EPYC-7763
    env:
      test-file: cpu_test.log

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.artifact }}

      - name: Unarchive artifact
        run: |
          tar xzf ${{ env.artifact }}
          rm ${{ env.artifact }}

      - name: Run tests
        working-directory: ${{ env.build_dir }}/tests
        run: |
          ./cuboolgraph_tests | tee ${{ env.test-file }}

      - name: Upload tests resutls
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.test-file }}
          path: ${{ env.build_dir }}/tests/${{ env.test-file }}

      - name: Check for unit tests results
        working-directory: ${{ env.build_dir }}/tests
        run: |
          ! grep -q "FAILED" ${{ env.test-file }}
